
#ifdef KEYPAD_DIR_NUMBER
static const U8 g_DKTable[KEYPAD_DIR_NUMBER] = {0};
#endif

static const U8 g_MKTable[KEYPAD_ROW_NUMBER][KEYPAD_COL_NUMBER] = {
        {KEY_FUNCTION_DIR_UP,       KEY_FUNCTION_DIR_DOWN,      KEY_FUNCTION_DIR_LEFT,  KEY_FUNCTION_DIR_RIGHT},
        {KEY_FUNCTION_CALL,         KEY_FUNCTION_HANGUP,        KEY_FUNCTION_ACTION,    KEY_FUNCTION_CAMERA},
        {KEY_FUNCTION_VOLUME_PLUS,  KEY_FUNCTION_VOLUME_MINUS,  0,                      0}
};

#define KEYPAD_EVENT_TABLE
static const Event_Flag_t g_MKEventTable[KEYPAD_ROW_NUMBER][KEYPAD_COL_NUMBER] = {
        {MAIN_EVENT_NULL, MAIN_EVENT_NULL, MAIN_EVENT_NULL, MAIN_EVENT_NULL},
        {MAIN_EVENT_NULL, MAIN_EVENT_NULL, MAIN_EVENT_NULL, MAIN_EVENT_CAMERA},
        {MAIN_EVENT_NULL, MAIN_EVENT_NULL, MAIN_EVENT_NULL, MAIN_EVENT_NULL}
};

