
/*
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    Logic Address

    PLEASE Check link script file and _MemoryMap*.inc

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

/*
    System Memory Space
*/

// 1
#define SYS_SRAM_BASE                   0x5C000000
#define SYS_SRAM_SIZE                   PHISICAL_SRAM_SIZE
#define SYS_SRAM_TOP                    (SYS_SRAM_BASE + SYS_SRAM_SIZE)
// 2
#define SYS_SDRAM_BASE                  0x80000000
#define SYS_SDRAM_SIZE                  PHISICAL_SDRAM_SIZE
#define SYS_SDRAM_TOP                   (SYS_SDRAM_BASE + SYS_SDRAM_SIZE)

/*
    SDRAM Mmeory Allocate
*/

// 1.1
#define BUFFER_DISPLAY_SIZE             (2 * 1024 * 1024)
// 1.2
#define RUNTIME_APPLICATION_SIZE        (1 * 1024 * 1024)
// 1.3
#define RUNTIME_PROGRAM_SIZE            (1 * 1024 * 1024)
// 1.4
#if (RUNTIME_PROGRAM_SIZE + RUNTIME_APPLICATION_SIZE + BUFFER_DISPLAY_SIZE) > SYS_SDRAM_SIZE
#error "OUT OF SDRAM SPACE"
#endif
#define BUFFER_RAM_DISK_SIZE            (SYS_SDRAM_SIZE - BUFFER_DISPLAY_SIZE - RUNTIME_APPLICATION_SIZE - RUNTIME_PROGRAM_SIZE)

// 1.3.1
#define EXE_RUNTIME_SPACE_SIZE          (256 * 1024)
// 1.3.3
#define EXE_STACK_INDIVIDUAL_SIZE       (16 * 1024)
#define EXE_STACK_TOTAL_SIZE            (6 * EXE_STACK_INDIVIDUAL_SIZE)
// 1.3.2
#if (EXE_STACK_TOTAL_SIZE + EXE_RUNTIME_SPACE_SIZE) > RUNTIME_PROGRAM_SIZE
#error "OUT OF PROGRAM SPACE"
#endif
#define BUFFER_SHARED_UNION_SIZE        (RUNTIME_PROGRAM_SIZE - EXE_RUNTIME_SPACE_SIZE - EXE_STACK_TOTAL_SIZE)
// 1.1.1
#define FB_BASE_RGB565_SIZE             ((LCD_WIDTH * LCD_HEIGHT) * (FB_BASE_BPP/8))
// 1.1.2
#define FB_OVERLAY1_RGB_SIZE            ((OVERLAY1_WIDTH * OVERLAY1_HEIGHT) * (LCD_OL1_BPP/8))
// 1.1.3
#define FB_OVERLAY2_RGB_SIZE            ((OVERLAY2_WIDTH * OVERLAY2_HEIGHT) * (LCD_OL2_BPP/8))
// 1.1.4
#define FB_OVERLAY2_Y_SIZE              ((OVERLAY2_WIDTH * OVERLAY2_HEIGHT))
// 1.1.5
#define FB_OVERLAY2_U_SIZE              ((OVERLAY2_WIDTH * OVERLAY2_HEIGHT)/2)
// 1.1.6
#define FB_OVERLAY2_V_SIZE              ((OVERLAY2_WIDTH * OVERLAY2_HEIGHT)/2)
#if (FB_BASE_RGB565_SIZE + FB_OVERLAY1_RGB_SIZE + FB_OVERLAY2_RGB_SIZE + FB_OVERLAY2_Y_SIZE + FB_OVERLAY2_U_SIZE + FB_OVERLAY2_V_SIZE) > BUFFER_DISPLAY_SIZE
#error "OUT OF DISPLAY SPACE"
#endif

/*
    SDRAM Mmeory Map
*/

// 1.1
#define BUFFER_DISPLAY_BASE             SYS_SDRAM_BASE
// 1.2
#define RUNTIME_APPLICATION_BASE        (BUFFER_DISPLAY_BASE + BUFFER_DISPLAY_SIZE)
// 1.3
#define RUNTIME_PROGRAM_BASE            (RUNTIME_APPLICATION_BASE + RUNTIME_APPLICATION_SIZE)
// 1.4
#define BUFFER_RAM_DISK_BASE            (RUNTIME_PROGRAM_BASE + RUNTIME_PROGRAM_SIZE)
// 1.1.1
#define EXE_IMAGE_BASE                  (RUNTIME_PROGRAM_BASE)
// 1.1.2
#define BUFFER_SHARED_UNION_BASE        (EXE_IMAGE_BASE + EXE_RUNTIME_SPACE_SIZE)
// 1.1.3
#define EXE_STACK_BASE                  (BUFFER_SHARED_UNION_BASE + BUFFER_SHARED_UNION_SIZE)
#define EXE_STACK_TOP                   (EXE_STACK_BASE + EXE_STACK_TOTAL_SIZE)
#define EXE_STACK_LAST                  (EXE_STACK_TOP - 4)
#if (RUNTIME_PROGRAM_BASE + RUNTIME_PROGRAM_SIZE) != EXE_STACK_TOP
#error "Not match"
#endif

// 1.3.1
#define FB_BASE_RGB565_ADDR             (BUFFER_DISPLAY_BASE)
// 1.3.2
#define FB_OVERLAY1_RGB_ADDR            (FB_BASE_RGB565_ADDR + FB_BASE_RGB565_SIZE)
// 1.3.3
#define FB_OVERLAY2_RGB_ADDR            (FB_OVERLAY1_RGB_ADDR + FB_OVERLAY1_RGB_SIZE)
// 1.3.4
#define FB_OVERLAY2_Y_ADDR              (FB_OVERLAY1_RGB_ADDR + FB_OVERLAY1_RGB_SIZE)
// 1.3.5
#define FB_OVERLAY2_U_ADDR              (FB_OVERLAY2_Y_ADDR + FB_OVERLAY2_Y_SIZE)
// 1.3.6
#define FB_OVERLAY2_V_ADDR              (FB_OVERLAY2_U_ADDR + FB_OVERLAY2_U_SIZE)

/*
    SRAM Mmeory Map
*/

#define RESERVED_ERRATA_5_ADDR          (SYS_SRAM_BASE)
#define RESERVED_ERRATA_5_SIZE          (1 * 1024)

#define RESERVED_UUID_ADDR              (RESERVED_ERRATA_5_ADDR + RESERVED_ERRATA_5_SIZE)
#define RESERVED_UUID_SIZE              (0x30)

#define RESERVED_NTIM_ADDR              (0x5C008000)        // This must be same as the NTIM setting
#define RESERVED_NTIM_SIZE              (NAND_SECTOR_SIZE)

// DMA Descriptor

#define BUFFER_DMA_DESC_ADDR            (RESERVED_NTIM_ADDR + RESERVED_NTIM_SIZE)

// We want to use a descriptor link to test some use cases

#define DISCRETE_FRAME_NUMBER           4
#define DMA_DESC_LCD_BASE_ADDR          (BUFFER_DMA_DESC_ADDR)
#define DMA_DESC_LCD_BASE_SIZE          (LCD_DMA_DESC_SIZE * DISCRETE_FRAME_NUMBER)

#define DMA_DESC_LCD_OL1_RGB_ADDR       (DMA_DESC_LCD_BASE_ADDR + DMA_DESC_LCD_BASE_SIZE)
#define DMA_DESC_LCD_OL1_RGB_SIZE       LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_OL2_RGB_ADDR       (DMA_DESC_LCD_OL1_RGB_ADDR + DMA_DESC_LCD_OL1_RGB_SIZE)
#define DMA_DESC_LCD_OL2_RGB_SIZE       LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_OL2_Y_ADDR         (DMA_DESC_LCD_OL2_RGB_ADDR + DMA_DESC_LCD_OL2_RGB_SIZE)
#define DMA_DESC_LCD_OL2_Y_SIZE         LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_OL2_U_ADDR         (DMA_DESC_LCD_OL2_Y_ADDR + DMA_DESC_LCD_OL2_Y_SIZE)
#define DMA_DESC_LCD_OL2_U_SIZE         LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_OL2_V_ADDR         (DMA_DESC_LCD_OL2_U_ADDR + DMA_DESC_LCD_OL2_U_SIZE)
#define DMA_DESC_LCD_OL2_V_SIZE         LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_BRANCH_ADDR        (DMA_DESC_LCD_OL2_V_ADDR + DMA_DESC_LCD_OL2_V_SIZE)
#define DMA_DESC_LCD_BRANCH_SIZE        LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_BRANCH_Y_ADDR      (DMA_DESC_LCD_BRANCH_ADDR + DMA_DESC_LCD_BRANCH_SIZE)
#define DMA_DESC_LCD_BRANCH_Y_SIZE      LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_BRANCH_U_ADDR      (DMA_DESC_LCD_BRANCH_Y_ADDR + DMA_DESC_LCD_BRANCH_Y_SIZE)
#define DMA_DESC_LCD_BRANCH_U_SIZE      LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_BRANCH_V_ADDR      (DMA_DESC_LCD_BRANCH_U_ADDR + DMA_DESC_LCD_BRANCH_U_SIZE)
#define DMA_DESC_LCD_BRANCH_V_SIZE      LCD_DMA_DESC_SIZE

#define DMA_DESC_LCD_PALETTE_ADDR       (DMA_DESC_LCD_BRANCH_V_ADDR + DMA_DESC_LCD_BRANCH_V_SIZE)
#define DMA_DESC_LCD_PALETTTE_SIZE      LCD_DMA_DESC_SIZE

#define DMA_DESC_CIF_RGB_ADDR           (DMA_DESC_LCD_PALETTE_ADDR + DMA_DESC_LCD_PALETTTE_SIZE)
#define DMA_DESC_CIF_RGB_SIZE           CIF_DMA_DESC_SIZE

#define DMA_DESC_CIF_Y_ADDR             (DMA_DESC_CIF_RGB_ADDR + DMA_DESC_CIF_RGB_SIZE)
#define DMA_DESC_CIF_Y_SIZE             CIF_DMA_DESC_SIZE

#define DMA_DESC_CIF_U_ADDR             (DMA_DESC_CIF_Y_ADDR + DMA_DESC_CIF_Y_SIZE)
#define DMA_DESC_CIF_U_SIZE             CIF_DMA_DESC_SIZE

#define DMA_DESC_CIF_V_ADDR             (DMA_DESC_CIF_U_ADDR + DMA_DESC_CIF_U_SIZE)
#define DMA_DESC_CIF_V_SIZE             CIF_DMA_DESC_SIZE

#define DMA_END_ADDR                    (DMA_DESC_CIF_V_ADDR + DMA_DESC_CIF_V_SIZE)

#if (SYS_SRAM_BASE + SYS_SRAM_SIZE) < DMA_END_ADDR
#error "OUT OF SRAM"
#endif


